apiVersion: v1
kind: Service
metadata:
  name: n8n-service 
  namespace: n8n
  annotations:
    # Annotations pour Application Gateway for Containers (AGC)
    service.beta.kubernetes.io/azure-load-balancer-internal: "false"
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5678 
      name: http
  selector:
    app: n8n-main 

---

apiVersion: v1
kind: Service
metadata:
  name: n8n-worker-service
  namespace: n8n
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5678
      name: http
  selector:
    app: n8n-workers