# k8s/n8n-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: n8n-sensitive-secrets
  namespace: default
type: Opaque
data:
  N8N_ENCRYPTION_KEY: <N8N_ENCRYPTION_KEY_BASE64> 
  DB_USER: <DB_USER_BASE64>
  DB_PASSWORD: <DB_PASSWORD_BASE64>
  QUEUE_BULL_REDIS_PASSWORD: <QUEUE_BULL_REDIS_PASSWORD_BASE64>