name: n8n

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  TF_WORKING_DIR: ../../terraform
  TF_POSTGRES_USER: n8nadmin 
  ARM_CLIENT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
  ARM_CLIENT_SECRET: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}
  ARM_SUBSCRIPTION_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
  ARM_TENANT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}

jobs:
  terraform_validate:
    name: Validate Terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -backend-config="storage_account_name=stoynovgroup"

      - name: Terraform fmt
        run: terraform fmt -check 

      - name: Terraform Validate
        run: terraform validate

  terraform_plan:
    name: Plan
    runs-on: ubuntu-latest
    needs: [terraform_validate]

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init -backend-config="storage_account_name=stoynovgroup"

      - name: Terraform Plan
        run: terraform plan -out=tfplan -var "pg_admin_password=${{ secrets.TF_POSTGRES_PASSWORD }}"

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan

  deploy_infra_and_app:
    name: Deploy Infra & App
    runs-on: ubuntu-latest
    needs: [terraform_plan]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    environment: production

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init -backend-config="storage_account_name=stoynovgroup"

      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: ./terraform/

      - name: Terraform Apply
        run: terraform apply tfplan

      - name: Terraform Output
        id: output
        run: |
          echo "ACR_SERVER=$(terraform output -raw acr_login_server)" >> $GITHUB_OUTPUT
          echo "KUBE_CONFIG=$(terraform output -raw kube_config)" >> $GITHUB_OUTPUT
          echo "REDIS_KEY=$(terraform output -raw redis_primary_key)" >> $GITHUB_OUTPUT

      - name: ACR Login
        uses: azure/docker-login@v2
        with:
          login-server: ${{ steps.output.outputs.ACR_SERVER }}
          username: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
          password: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}

      - name: Build and Push Image to ACR
        id: build_image
        env:
          ACR_PATH: ${{ steps.output.outputs.ACR_SERVER }}/n8n-custom:${{ github.sha }}
        run: |
          docker build -t $ACR_PATH .
          docker push $ACR_PATH

      - name: Kubernetes
        run: |
          mkdir -p ~/.kube
          echo "${{ steps.output.outputs.KUBE_CONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config

          ENCRYPTION_KEY_B64=$(echo -n "${{ secrets.N8N_ENCRYPTION_KEY }}" | base64)
          PG_PASS_B64=$(echo -n "${{ secrets.TF_POSTGRES_PASSWORD }}" | base64)
          REDIS_KEY_B64=$(echo -n "${{ steps.output.outputs.REDIS_KEY }}" | base64)
          PG_USER_B64=$(echo -n "${{ env.TF_POSTGRES_USER }}" | base64)

          sed -i "s|<N8N_ENCRYPTION_KEY_BASE64>|$ENCRYPTION_KEY_B64|g" ./k8s/n8n-secret.yaml
          sed -i "s|<DB_USER_BASE64>|$PG_USER_B64|g" ./k8s/n8n-secret.yaml
          sed -i "s|<DB_PASSWORD_BASE64>|$PG_PASS_B64|g" ./k8s/n8n-secret.yaml
          sed -i "s|<QUEUE_BULL_REDIS_PASSWORD_BASE64>|$REDIS_KEY_B64|g" ./k8s/n8n-secret.yaml
          
          kubectl apply -f ./k8s/n8n-secret.yaml
          kubectl apply -f ./k8s/n8n-configmap.yaml
          
          ACR_PATH="${{ steps.output.outputs.ACR_SERVER }}/n8n-custom:${{ github.sha }}"
          sed -i "s|REPLACE_IMAGE_WITH_ACR_PATH:TAG|$ACR_PATH|g" ./k8s/n8n-deployments.yaml
          
          kubectl apply -f ./k8s/n8n-deployments.yaml
          kubectl apply -f ./k8s/n8n-services.yaml
          
          kubectl rollout status statefulset/n8n-main -n default --timeout=300s